# main site metadata and titles
site_name: Miranda Docs
site_description: Docs site for Miranda 
site_author: Dr Anchit Chandran
# site_url: https://medicode.info/

# copyright information which is shown in the footer
copyright: FREE OPEN SOURCE

# these lines configure the 'GitHub repo' widget on the top right
# repo_url: https://github.com/anchit-chandran/medicode-website
repo_name: anchit-chandran/mira-man-mkdoc

# `mkdocs serve` serves the documentation at custom port
dev_addr: "127.0.0.1:8001"


nav:
  - "index.md"
  - Meta: 
    - About the name 'Miranda': "2.md"
    - About this release: "3.md"
  - Miranda command interpreter: 
    - "4.md"
    - Summary of main commands: "5.md"
    - Remaining commands list: "6.md"
  - Main Concepts:
    - Expressions: "7.md"
    - Operators & Binding: "8.md"
    - Sections: "9.md"
    - Identifiers: "10.md"
    - Literals: "11.md"
    - Tokenisation and layout: "12.md"
    - Iterative Expressions:
      - Dotdot notation: "13-1.md"
      - List comprehensions: "13-2.md"
      - Diagonalising list comprehensions: "13-3.md"
    - "14.md"
    - Definitions: "15.md"
    - "16.md"
    - "17.md"
    - "18.md"
    - "19.md"
    - "20.md"
    - "21.md"
    - "22.md"
    - "23.md"
    - "24.md"
    - "25.md"
    - "26.md"
    - "28.md"
    - "29.md"
    - "30.md"



theme:
  name: material 
  features:
    - navigation.expand
    # - header.autohide
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate
    - toc.follow

  palette:
    scheme: dark
  font:
    text: Roboto Mono
    code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
# extra:
#   social:
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/medic_ode
#     - icon: fontawesome/brands/instagram
#       link: https://www.instagram.com/medic_ode/

